### ISSUE TITLE
sort inner modules for last

### ISSUE THREAD

**Issue by cusspvz** [worldiety/goup#5] opened 2020-01-06 19:56 UTC
![image](https://user-images.githubusercontent.com/3604053/71844638-7a2e5e00-30be-11ea-8619-9639a09145e1.png)

This situation causes an error since `/Users/josemoreira/.goup/RNIPFS/go/src/go.opencensus.io/stats` will always exist due to the fact that the module `/Users/josemoreira/.goup/RNIPFS/go/src/go.opencensus.io/stats/view` gets copied over before.

**Comment by torbenschinke** [comment] 2020-01-14 13:48
Actually, I cannot reproduce the resolving issue. For me it looks like it is sorted correctly:
```
2020-01-14 14:43:51.339 [DEBUG] - exec: go mod vendor , 
2020-01-14 14:43:51.401 [DEBUG] - : , 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io, version: v0.22.2, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io, version: v0.22.2, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/stats, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/stats, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/stats/view, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/stats/view, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/metric/metricdata, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/metric/metricdata, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/stats/internal, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/stats/internal, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/tag, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/tag, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/internal/tagencoding, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/internal/tagencoding, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/metric/metricproducer, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/metric/metricproducer, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: found, module: go.opencensus.io/resource, version: v0.0.0, 
2020-01-14 14:43:51.401 [DEBUG] - action: upgrade, module: go.opencensus.io/resource, version: v0.0.0, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io, msg: already absent, has been moved?, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/tag, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/tag, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/tag, msg: already absent, has been moved?, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/stats, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/stats, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/stats, msg: already absent, has been moved?, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/resource, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/resource, 
2020-01-14 14:43:51.407 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/resource, msg: already absent, has been moved?, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/stats/view, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/stats/view, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/stats/view, msg: already absent, has been moved?, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/stats/internal, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/stats/internal, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/stats/internal, msg: already absent, has been moved?, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/metric/metricdata, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/metric/metricdata, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/metric/metricdata, msg: already absent, has been moved?, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/internal/tagencoding, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/internal/tagencoding, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/internal/tagencoding, msg: already absent, has been moved?, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/metric/metricproducer, to: /Users/tschinke/.goup/issue5/go/src/go.opencensus.io/metric/metricproducer, 
2020-01-14 14:43:51.408 [DEBUG] - action: move, from: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor/go.opencensus.io/metric/metricproducer, msg: already absent, has been moved?, 
2020-01-14 14:43:51.408 [DEBUG] - action: remove, file: /Users/tschinke/.goup/issue5/go/src/github.com/fatlib/vendor, 
```
Which version of GoUp do you use?
```
2020-01-14 14:43:51.241 [DEBUG] - GOARCH: amd64, GOOS: darwin, Name: GoUp, Version: 0.0.15, 
```

**Comment by torbenschinke** [comment] 2024-06-11 11:00
cannot reproduce

**Closed as completed by torbenschinke** 2024-06-11 11:00 UTC
